### ISSUE TITLE
Request to update README.md

### ISSUE THREAD

**Issue by malinskibeniamin** [Jamesyang2333/ntu-course-planning-system#1]
Hi there,

I have been trying to use this tool for planning my courses. I really appreciate the initiative! However, it is not very clear how to proceed.
Right now I have managed to:
1) Install virtualenv
2) Activate it
3) Use pip to install python3 and django
4) Set up database privileges so that it will work with root access
5) Create an empty MySQL database 'courses'
I am stuck at a point where I run 'python3 manage.py runserver'. Upon reaching http://127.0.0.1:8000/, I keep getting "404 Not Found" for the GET request. Which commands should be run now to be able to add/remove courses? Should I do it manually from the CLI for the database?

Thanks again for developing this, I will be looking forward to your answers.

**Comment by Jamesyang2333** [comment]
Hey, 

Thanks for pointing this out. My apology for not having a detailed README, as this project was previously a personal side project. We'll update the README file by this week to include instructions on environment set-up and how to launch the website from your own computer.

To address the problem you encountered, you need to create a table of specific format in the database to store the course data. And when you start the Django server, the main site address would be http://127.0.0.1:8000/home. Pls refer to README after it is updated later this week, things would be clearer by then. 

-James

**Comment by Jamesyang2333** [comment]
Hey Beniamin, the README file has been updated! Do let me know if there's any questions about it.
